name = "PlutoVTKPlot"
uuid = "19f70b67-2887-4cf9-b19e-fe1a30c34d85"
authors = ["Juergen Fuhrmann <juergen.fuhrmann@wias-berlin.de>"]
version = "0.0.1"

[deps]
PlutoCanvasPlot = "57876ffe-7b7d-4c51-befe-9eb7dc4baaca"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
